// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: grpctest.proto

package grpc_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Basic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vsint32       int32                  `protobuf:"zigzag32,1,opt,name=vsint32,proto3" json:"vsint32,omitempty"`
	Vsint64       int64                  `protobuf:"zigzag64,2,opt,name=vsint64,proto3" json:"vsint64,omitempty"`
	Vuint32       uint32                 `protobuf:"varint,3,opt,name=vuint32,proto3" json:"vuint32,omitempty"`
	Vuint64       uint64                 `protobuf:"varint,4,opt,name=vuint64,proto3" json:"vuint64,omitempty"`
	Vsfixed32     int32                  `protobuf:"fixed32,5,opt,name=vsfixed32,proto3" json:"vsfixed32,omitempty"`
	Vsfixed64     int64                  `protobuf:"fixed64,6,opt,name=vsfixed64,proto3" json:"vsfixed64,omitempty"`
	Vfixed32      uint32                 `protobuf:"fixed32,7,opt,name=vfixed32,proto3" json:"vfixed32,omitempty"`
	Vfixed64      uint64                 `protobuf:"fixed64,8,opt,name=vfixed64,proto3" json:"vfixed64,omitempty"`
	Vfloat        float32                `protobuf:"fixed32,9,opt,name=vfloat,proto3" json:"vfloat,omitempty"`
	Vdouble       float64                `protobuf:"fixed64,10,opt,name=vdouble,proto3" json:"vdouble,omitempty"`
	Vboolt        bool                   `protobuf:"varint,11,opt,name=vboolt,proto3" json:"vboolt,omitempty"`
	Vboolf        bool                   `protobuf:"varint,12,opt,name=vboolf,proto3" json:"vboolf,omitempty"`
	Vstring       string                 `protobuf:"bytes,13,opt,name=vstring,proto3" json:"vstring,omitempty"`
	Vbytes        []byte                 `protobuf:"bytes,14,opt,name=vbytes,proto3" json:"vbytes,omitempty"`
	Vint32        int32                  `protobuf:"varint,15,opt,name=vint32,proto3" json:"vint32,omitempty"`
	Vint64        int64                  `protobuf:"varint,16,opt,name=vint64,proto3" json:"vint64,omitempty"`
	Vint32_1      int32                  `protobuf:"varint,17,opt,name=vint32_1,json=vint321,proto3" json:"vint32_1,omitempty"`
	Vint64_2      int64                  `protobuf:"varint,18,opt,name=vint64_2,json=vint642,proto3" json:"vint64_2,omitempty"`
	Vsint32_1     int32                  `protobuf:"zigzag32,19,opt,name=vsint32_1,json=vsint321,proto3" json:"vsint32_1,omitempty"`
	Vsint64_2     int64                  `protobuf:"zigzag64,20,opt,name=vsint64_2,json=vsint642,proto3" json:"vsint64_2,omitempty"`
	Vsfixed32_1   int32                  `protobuf:"fixed32,21,opt,name=vsfixed32_1,json=vsfixed321,proto3" json:"vsfixed32_1,omitempty"`
	Vsfixed64_2   int64                  `protobuf:"fixed64,22,opt,name=vsfixed64_2,json=vsfixed642,proto3" json:"vsfixed64_2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Basic) Reset() {
	*x = Basic{}
	mi := &file_grpctest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Basic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Basic) ProtoMessage() {}

func (x *Basic) ProtoReflect() protoreflect.Message {
	mi := &file_grpctest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Basic.ProtoReflect.Descriptor instead.
func (*Basic) Descriptor() ([]byte, []int) {
	return file_grpctest_proto_rawDescGZIP(), []int{0}
}

func (x *Basic) GetVsint32() int32 {
	if x != nil {
		return x.Vsint32
	}
	return 0
}

func (x *Basic) GetVsint64() int64 {
	if x != nil {
		return x.Vsint64
	}
	return 0
}

func (x *Basic) GetVuint32() uint32 {
	if x != nil {
		return x.Vuint32
	}
	return 0
}

func (x *Basic) GetVuint64() uint64 {
	if x != nil {
		return x.Vuint64
	}
	return 0
}

func (x *Basic) GetVsfixed32() int32 {
	if x != nil {
		return x.Vsfixed32
	}
	return 0
}

func (x *Basic) GetVsfixed64() int64 {
	if x != nil {
		return x.Vsfixed64
	}
	return 0
}

func (x *Basic) GetVfixed32() uint32 {
	if x != nil {
		return x.Vfixed32
	}
	return 0
}

func (x *Basic) GetVfixed64() uint64 {
	if x != nil {
		return x.Vfixed64
	}
	return 0
}

func (x *Basic) GetVfloat() float32 {
	if x != nil {
		return x.Vfloat
	}
	return 0
}

func (x *Basic) GetVdouble() float64 {
	if x != nil {
		return x.Vdouble
	}
	return 0
}

func (x *Basic) GetVboolt() bool {
	if x != nil {
		return x.Vboolt
	}
	return false
}

func (x *Basic) GetVboolf() bool {
	if x != nil {
		return x.Vboolf
	}
	return false
}

func (x *Basic) GetVstring() string {
	if x != nil {
		return x.Vstring
	}
	return ""
}

func (x *Basic) GetVbytes() []byte {
	if x != nil {
		return x.Vbytes
	}
	return nil
}

func (x *Basic) GetVint32() int32 {
	if x != nil {
		return x.Vint32
	}
	return 0
}

func (x *Basic) GetVint64() int64 {
	if x != nil {
		return x.Vint64
	}
	return 0
}

func (x *Basic) GetVint32_1() int32 {
	if x != nil {
		return x.Vint32_1
	}
	return 0
}

func (x *Basic) GetVint64_2() int64 {
	if x != nil {
		return x.Vint64_2
	}
	return 0
}

func (x *Basic) GetVsint32_1() int32 {
	if x != nil {
		return x.Vsint32_1
	}
	return 0
}

func (x *Basic) GetVsint64_2() int64 {
	if x != nil {
		return x.Vsint64_2
	}
	return 0
}

func (x *Basic) GetVsfixed32_1() int32 {
	if x != nil {
		return x.Vsfixed32_1
	}
	return 0
}

func (x *Basic) GetVsfixed64_2() int64 {
	if x != nil {
		return x.Vsfixed64_2
	}
	return 0
}

type Repeated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vsint32       []int32                `protobuf:"zigzag32,1,rep,packed,name=vsint32,proto3" json:"vsint32,omitempty"`
	Vsint64       []int64                `protobuf:"zigzag64,2,rep,packed,name=vsint64,proto3" json:"vsint64,omitempty"`
	Vuint32       []uint32               `protobuf:"varint,3,rep,packed,name=vuint32,proto3" json:"vuint32,omitempty"`
	Vuint64       []uint64               `protobuf:"varint,4,rep,packed,name=vuint64,proto3" json:"vuint64,omitempty"`
	Vsfixed32     []int32                `protobuf:"fixed32,5,rep,packed,name=vsfixed32,proto3" json:"vsfixed32,omitempty"`
	Vsfixed64     []int64                `protobuf:"fixed64,6,rep,packed,name=vsfixed64,proto3" json:"vsfixed64,omitempty"`
	Vfixed32      []uint32               `protobuf:"fixed32,7,rep,packed,name=vfixed32,proto3" json:"vfixed32,omitempty"`
	Vfixed64      []uint64               `protobuf:"fixed64,8,rep,packed,name=vfixed64,proto3" json:"vfixed64,omitempty"`
	Vfloat        []float32              `protobuf:"fixed32,9,rep,packed,name=vfloat,proto3" json:"vfloat,omitempty"`
	Vdouble       []float64              `protobuf:"fixed64,10,rep,packed,name=vdouble,proto3" json:"vdouble,omitempty"`
	Vboolt        []bool                 `protobuf:"varint,11,rep,packed,name=vboolt,proto3" json:"vboolt,omitempty"`
	Vboolf        []bool                 `protobuf:"varint,12,rep,packed,name=vboolf,proto3" json:"vboolf,omitempty"`
	Vstring       []string               `protobuf:"bytes,13,rep,name=vstring,proto3" json:"vstring,omitempty"`
	Vbytes        [][]byte               `protobuf:"bytes,14,rep,name=vbytes,proto3" json:"vbytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repeated) Reset() {
	*x = Repeated{}
	mi := &file_grpctest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repeated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repeated) ProtoMessage() {}

func (x *Repeated) ProtoReflect() protoreflect.Message {
	mi := &file_grpctest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repeated.ProtoReflect.Descriptor instead.
func (*Repeated) Descriptor() ([]byte, []int) {
	return file_grpctest_proto_rawDescGZIP(), []int{1}
}

func (x *Repeated) GetVsint32() []int32 {
	if x != nil {
		return x.Vsint32
	}
	return nil
}

func (x *Repeated) GetVsint64() []int64 {
	if x != nil {
		return x.Vsint64
	}
	return nil
}

func (x *Repeated) GetVuint32() []uint32 {
	if x != nil {
		return x.Vuint32
	}
	return nil
}

func (x *Repeated) GetVuint64() []uint64 {
	if x != nil {
		return x.Vuint64
	}
	return nil
}

func (x *Repeated) GetVsfixed32() []int32 {
	if x != nil {
		return x.Vsfixed32
	}
	return nil
}

func (x *Repeated) GetVsfixed64() []int64 {
	if x != nil {
		return x.Vsfixed64
	}
	return nil
}

func (x *Repeated) GetVfixed32() []uint32 {
	if x != nil {
		return x.Vfixed32
	}
	return nil
}

func (x *Repeated) GetVfixed64() []uint64 {
	if x != nil {
		return x.Vfixed64
	}
	return nil
}

func (x *Repeated) GetVfloat() []float32 {
	if x != nil {
		return x.Vfloat
	}
	return nil
}

func (x *Repeated) GetVdouble() []float64 {
	if x != nil {
		return x.Vdouble
	}
	return nil
}

func (x *Repeated) GetVboolt() []bool {
	if x != nil {
		return x.Vboolt
	}
	return nil
}

func (x *Repeated) GetVboolf() []bool {
	if x != nil {
		return x.Vboolf
	}
	return nil
}

func (x *Repeated) GetVstring() []string {
	if x != nil {
		return x.Vstring
	}
	return nil
}

func (x *Repeated) GetVbytes() [][]byte {
	if x != nil {
		return x.Vbytes
	}
	return nil
}

type Embedded struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	F1            *Basic                 `protobuf:"bytes,1,opt,name=f1,proto3" json:"f1,omitempty"`
	F2            *Repeated              `protobuf:"bytes,2,opt,name=f2,proto3" json:"f2,omitempty"`
	F3            []*Basic               `protobuf:"bytes,3,rep,name=f3,proto3" json:"f3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Embedded) Reset() {
	*x = Embedded{}
	mi := &file_grpctest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Embedded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Embedded) ProtoMessage() {}

func (x *Embedded) ProtoReflect() protoreflect.Message {
	mi := &file_grpctest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Embedded.ProtoReflect.Descriptor instead.
func (*Embedded) Descriptor() ([]byte, []int) {
	return file_grpctest_proto_rawDescGZIP(), []int{2}
}

func (x *Embedded) GetF1() *Basic {
	if x != nil {
		return x.F1
	}
	return nil
}

func (x *Embedded) GetF2() *Repeated {
	if x != nil {
		return x.F2
	}
	return nil
}

func (x *Embedded) GetF3() []*Basic {
	if x != nil {
		return x.F3
	}
	return nil
}

var File_grpctest_proto protoreflect.FileDescriptor

const file_grpctest_proto_rawDesc = "" +
	"\n" +
	"\x0egrpctest.proto\x12\bgrpc_api\"\xd9\x04\n" +
	"\x05Basic\x12\x18\n" +
	"\avsint32\x18\x01 \x01(\x11R\avsint32\x12\x18\n" +
	"\avsint64\x18\x02 \x01(\x12R\avsint64\x12\x18\n" +
	"\avuint32\x18\x03 \x01(\rR\avuint32\x12\x18\n" +
	"\avuint64\x18\x04 \x01(\x04R\avuint64\x12\x1c\n" +
	"\tvsfixed32\x18\x05 \x01(\x0fR\tvsfixed32\x12\x1c\n" +
	"\tvsfixed64\x18\x06 \x01(\x10R\tvsfixed64\x12\x1a\n" +
	"\bvfixed32\x18\a \x01(\aR\bvfixed32\x12\x1a\n" +
	"\bvfixed64\x18\b \x01(\x06R\bvfixed64\x12\x16\n" +
	"\x06vfloat\x18\t \x01(\x02R\x06vfloat\x12\x18\n" +
	"\avdouble\x18\n" +
	" \x01(\x01R\avdouble\x12\x16\n" +
	"\x06vboolt\x18\v \x01(\bR\x06vboolt\x12\x16\n" +
	"\x06vboolf\x18\f \x01(\bR\x06vboolf\x12\x18\n" +
	"\avstring\x18\r \x01(\tR\avstring\x12\x16\n" +
	"\x06vbytes\x18\x0e \x01(\fR\x06vbytes\x12\x16\n" +
	"\x06vint32\x18\x0f \x01(\x05R\x06vint32\x12\x16\n" +
	"\x06vint64\x18\x10 \x01(\x03R\x06vint64\x12\x19\n" +
	"\bvint32_1\x18\x11 \x01(\x05R\avint321\x12\x19\n" +
	"\bvint64_2\x18\x12 \x01(\x03R\avint642\x12\x1b\n" +
	"\tvsint32_1\x18\x13 \x01(\x11R\bvsint321\x12\x1b\n" +
	"\tvsint64_2\x18\x14 \x01(\x12R\bvsint642\x12\x1f\n" +
	"\vvsfixed32_1\x18\x15 \x01(\x0fR\n" +
	"vsfixed321\x12\x1f\n" +
	"\vvsfixed64_2\x18\x16 \x01(\x10R\n" +
	"vsfixed642\"\xfa\x02\n" +
	"\bRepeated\x12\x18\n" +
	"\avsint32\x18\x01 \x03(\x11R\avsint32\x12\x18\n" +
	"\avsint64\x18\x02 \x03(\x12R\avsint64\x12\x18\n" +
	"\avuint32\x18\x03 \x03(\rR\avuint32\x12\x18\n" +
	"\avuint64\x18\x04 \x03(\x04R\avuint64\x12\x1c\n" +
	"\tvsfixed32\x18\x05 \x03(\x0fR\tvsfixed32\x12\x1c\n" +
	"\tvsfixed64\x18\x06 \x03(\x10R\tvsfixed64\x12\x1a\n" +
	"\bvfixed32\x18\a \x03(\aR\bvfixed32\x12\x1a\n" +
	"\bvfixed64\x18\b \x03(\x06R\bvfixed64\x12\x16\n" +
	"\x06vfloat\x18\t \x03(\x02R\x06vfloat\x12\x18\n" +
	"\avdouble\x18\n" +
	" \x03(\x01R\avdouble\x12\x16\n" +
	"\x06vboolt\x18\v \x03(\bR\x06vboolt\x12\x16\n" +
	"\x06vboolf\x18\f \x03(\bR\x06vboolf\x12\x18\n" +
	"\avstring\x18\r \x03(\tR\avstring\x12\x16\n" +
	"\x06vbytes\x18\x0e \x03(\fR\x06vbytes\"p\n" +
	"\bEmbedded\x12\x1f\n" +
	"\x02f1\x18\x01 \x01(\v2\x0f.grpc_api.BasicR\x02f1\x12\"\n" +
	"\x02f2\x18\x02 \x01(\v2\x12.grpc_api.RepeatedR\x02f2\x12\x1f\n" +
	"\x02f3\x18\x03 \x03(\v2\x0f.grpc_api.BasicR\x02f3B\x1dZ\x1btest/grpc_api_test;grpc_apib\x06proto3"

var (
	file_grpctest_proto_rawDescOnce sync.Once
	file_grpctest_proto_rawDescData []byte
)

func file_grpctest_proto_rawDescGZIP() []byte {
	file_grpctest_proto_rawDescOnce.Do(func() {
		file_grpctest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpctest_proto_rawDesc), len(file_grpctest_proto_rawDesc)))
	})
	return file_grpctest_proto_rawDescData
}

var file_grpctest_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpctest_proto_goTypes = []any{
	(*Basic)(nil),    // 0: grpc_api.Basic
	(*Repeated)(nil), // 1: grpc_api.Repeated
	(*Embedded)(nil), // 2: grpc_api.Embedded
}
var file_grpctest_proto_depIdxs = []int32{
	0, // 0: grpc_api.Embedded.f1:type_name -> grpc_api.Basic
	1, // 1: grpc_api.Embedded.f2:type_name -> grpc_api.Repeated
	0, // 2: grpc_api.Embedded.f3:type_name -> grpc_api.Basic
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_grpctest_proto_init() }
func file_grpctest_proto_init() {
	if File_grpctest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpctest_proto_rawDesc), len(file_grpctest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpctest_proto_goTypes,
		DependencyIndexes: file_grpctest_proto_depIdxs,
		MessageInfos:      file_grpctest_proto_msgTypes,
	}.Build()
	File_grpctest_proto = out.File
	file_grpctest_proto_goTypes = nil
	file_grpctest_proto_depIdxs = nil
}
