// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: multitenancy.proto

package tenancy_service_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tenant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	LongName      string                 `protobuf:"bytes,5,opt,name=long_name,json=longName,proto3" json:"long_name,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Active        string                 `protobuf:"bytes,7,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tenant) Reset() {
	*x = Tenant{}
	mi := &file_multitenancy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant) ProtoMessage() {}

func (x *Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_multitenancy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant.ProtoReflect.Descriptor instead.
func (*Tenant) Descriptor() ([]byte, []int) {
	return file_multitenancy_proto_rawDescGZIP(), []int{0}
}

func (x *Tenant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tenant) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Tenant) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Tenant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tenant) GetLongName() string {
	if x != nil {
		return x.LongName
	}
	return ""
}

func (x *Tenant) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tenant) GetActive() string {
	if x != nil {
		return x.Active
	}
	return ""
}

var File_multitenancy_proto protoreflect.FileDescriptor

const file_multitenancy_proto_rawDesc = "" +
	"\n" +
	"\x12multitenancy.proto\x12\x17tenancy_service_grpc.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf9\x01\n" +
	"\x06Tenant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1b\n" +
	"\tlong_name\x18\x05 \x01(\tR\blongName\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x16\n" +
	"\x06active\x18\a \x01(\tR\x06active2d\n" +
	"\x13MultitenancyService\x12M\n" +
	"\tAddTenant\x12\x1f.tenancy_service_grpc.v1.Tenant\x1a\x1f.tenancy_service_grpc.v1.TenantB7Z5pkg/multitenancy/tenancy_service/tenancy_service_grpcb\x06proto3"

var (
	file_multitenancy_proto_rawDescOnce sync.Once
	file_multitenancy_proto_rawDescData []byte
)

func file_multitenancy_proto_rawDescGZIP() []byte {
	file_multitenancy_proto_rawDescOnce.Do(func() {
		file_multitenancy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_multitenancy_proto_rawDesc), len(file_multitenancy_proto_rawDesc)))
	})
	return file_multitenancy_proto_rawDescData
}

var file_multitenancy_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_multitenancy_proto_goTypes = []any{
	(*Tenant)(nil),                // 0: tenancy_service_grpc.v1.Tenant
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_multitenancy_proto_depIdxs = []int32{
	1, // 0: tenancy_service_grpc.v1.Tenant.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: tenancy_service_grpc.v1.Tenant.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: tenancy_service_grpc.v1.MultitenancyService.AddTenant:input_type -> tenancy_service_grpc.v1.Tenant
	0, // 3: tenancy_service_grpc.v1.MultitenancyService.AddTenant:output_type -> tenancy_service_grpc.v1.Tenant
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_multitenancy_proto_init() }
func file_multitenancy_proto_init() {
	if File_multitenancy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_multitenancy_proto_rawDesc), len(file_multitenancy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_multitenancy_proto_goTypes,
		DependencyIndexes: file_multitenancy_proto_depIdxs,
		MessageInfos:      file_multitenancy_proto_msgTypes,
	}.Build()
	File_multitenancy_proto = out.File
	file_multitenancy_proto_goTypes = nil
	file_multitenancy_proto_depIdxs = nil
}
